version: 2

sources:
  - name: erp
    description: Fonte do SAP de vendas
    schema: erp_northwind
    tables:
      - name: products  
      - name: categories  
      - name: suppliers 
      - name: customers 
      - name: employees
      - name: data
      - name: orders
        description: Uma linha por pedido. Inclui pedidos cancelados e deletados.
        columns:
          - name: order_id
            tests:
              - unique
              - not_null
      - name: order_details 

  - name: dbt_northwind_cleber 
    description: Fonte de dados para dim tempo
    schema: erp_northwind
    tables: 
      - name: date  
 